package com.lampnc.businfo.entity;
// Generated Nov 18, 2016 5:58:34 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BusPathDetailId generated by hbm2java
 */
@Embeddable
public class BusPathDetailId implements java.io.Serializable {

	private int planId;
	private int orderNo;

	public BusPathDetailId() {
	}

	public BusPathDetailId(int planId, int orderNo) {
		this.planId = planId;
		this.orderNo = orderNo;
	}

	@Column(name = "PlanId", nullable = false)
	public int getPlanId() {
		return this.planId;
	}

	public void setPlanId(int planId) {
		this.planId = planId;
	}

	@Column(name = "OrderNo", nullable = false)
	public int getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(int orderNo) {
		this.orderNo = orderNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BusPathDetailId))
			return false;
		BusPathDetailId castOther = (BusPathDetailId) other;

		return (this.getPlanId() == castOther.getPlanId()) && (this.getOrderNo() == castOther.getOrderNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlanId();
		result = 37 * result + this.getOrderNo();
		return result;
	}

}
