package com.lampnc.businfo.entity;
// Generated Nov 18, 2016 5:58:34 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BusPathDetail generated by hbm2java
 */
@Entity
@Table(name = "BusPathDetail", schema = "dbo", catalog = "QuanLyXeBuyt")
public class BusPathDetail implements java.io.Serializable {

	private BusPathDetailId id;
	private BusRoutePlan busRoutePlan;
	private double latitude;
	private double longitude;

	public BusPathDetail() {
	}

	public BusPathDetail(BusPathDetailId id, BusRoutePlan busRoutePlan, double latitude, double longitude) {
		this.id = id;
		this.busRoutePlan = busRoutePlan;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "planId", column = @Column(name = "PlanId", nullable = false)),
			@AttributeOverride(name = "orderNo", column = @Column(name = "OrderNo", nullable = false)) })
	public BusPathDetailId getId() {
		return this.id;
	}

	public void setId(BusPathDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PlanId", nullable = false, insertable = false, updatable = false)
	public BusRoutePlan getBusRoutePlan() {
		return this.busRoutePlan;
	}

	public void setBusRoutePlan(BusRoutePlan busRoutePlan) {
		this.busRoutePlan = busRoutePlan;
	}

	@Column(name = "Latitude", nullable = false, precision = 12, scale = 9)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", nullable = false, precision = 12, scale = 9)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

}
