package com.lampnc.businfo.entity;
// Generated Nov 18, 2016 5:58:34 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BusStopDetail generated by hbm2java
 */
@Entity
@Table(name = "BusStopDetail", schema = "dbo", catalog = "QuanLyXeBuyt")
public class BusStopDetail implements java.io.Serializable {

	private BusStopDetailId id;
	private BusRoutePlan busRoutePlan;
	private BusStop busStop;
	private int orderNo;

	public BusStopDetail() {
	}

	public BusStopDetail(BusStopDetailId id, BusRoutePlan busRoutePlan, BusStop busStop, int orderNo) {
		this.id = id;
		this.busRoutePlan = busRoutePlan;
		this.busStop = busStop;
		this.orderNo = orderNo;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "planId", column = @Column(name = "PlanId", nullable = false)),
			@AttributeOverride(name = "stopId", column = @Column(name = "StopId", nullable = false)) })
	public BusStopDetailId getId() {
		return this.id;
	}

	public void setId(BusStopDetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PlanId", nullable = false, insertable = false, updatable = false)
	public BusRoutePlan getBusRoutePlan() {
		return this.busRoutePlan;
	}

	public void setBusRoutePlan(BusRoutePlan busRoutePlan) {
		this.busRoutePlan = busRoutePlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "StopId", nullable = false, insertable = false, updatable = false)
	public BusStop getBusStop() {
		return this.busStop;
	}

	public void setBusStop(BusStop busStop) {
		this.busStop = busStop;
	}

	@Column(name = "OrderNo", nullable = false)
	public int getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(int orderNo) {
		this.orderNo = orderNo;
	}

}
