package com.lampnc.businfo.entity;
// Generated Nov 18, 2016 5:58:34 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusTimeTable generated by hbm2java
 */
@Entity
@Table(name = "BusTimeTable", schema = "dbo", catalog = "QuanLyXeBuyt")
public class BusTimeTable implements java.io.Serializable {

	private BusTimeTableId id;
	private BusRoutePlan busRoutePlan;
	private String applyDates;
	private Date endDate;
	private String headway;
	private String operationTime;
	private String runningTime;
	private Date startDate;
	private int totalTrip;
	private short status;
	private Set<BusTrip> busTrips = new HashSet<BusTrip>(0);

	public BusTimeTable() {
	}

	public BusTimeTable(BusTimeTableId id, BusRoutePlan busRoutePlan, String applyDates, String headway,
			String operationTime, String runningTime, Date startDate, int totalTrip, short status) {
		this.id = id;
		this.busRoutePlan = busRoutePlan;
		this.applyDates = applyDates;
		this.headway = headway;
		this.operationTime = operationTime;
		this.runningTime = runningTime;
		this.startDate = startDate;
		this.totalTrip = totalTrip;
		this.status = status;
	}

	public BusTimeTable(BusTimeTableId id, BusRoutePlan busRoutePlan, String applyDates, Date endDate, String headway,
			String operationTime, String runningTime, Date startDate, int totalTrip, short status,
			Set<BusTrip> busTrips) {
		this.id = id;
		this.busRoutePlan = busRoutePlan;
		this.applyDates = applyDates;
		this.endDate = endDate;
		this.headway = headway;
		this.operationTime = operationTime;
		this.runningTime = runningTime;
		this.startDate = startDate;
		this.totalTrip = totalTrip;
		this.status = status;
		this.busTrips = busTrips;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "planId", column = @Column(name = "PlanId", nullable = false)),
			@AttributeOverride(name = "timeTableId", column = @Column(name = "TimeTableId", nullable = false)) })
	public BusTimeTableId getId() {
		return this.id;
	}

	public void setId(BusTimeTableId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PlanId", nullable = false, insertable = false, updatable = false)
	public BusRoutePlan getBusRoutePlan() {
		return this.busRoutePlan;
	}

	public void setBusRoutePlan(BusRoutePlan busRoutePlan) {
		this.busRoutePlan = busRoutePlan;
	}

	@Column(name = "ApplyDates", nullable = false)
	public String getApplyDates() {
		return this.applyDates;
	}

	public void setApplyDates(String applyDates) {
		this.applyDates = applyDates;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EndDate", length = 23)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "Headway", nullable = false)
	public String getHeadway() {
		return this.headway;
	}

	public void setHeadway(String headway) {
		this.headway = headway;
	}

	@Column(name = "OperationTime", nullable = false)
	public String getOperationTime() {
		return this.operationTime;
	}

	public void setOperationTime(String operationTime) {
		this.operationTime = operationTime;
	}

	@Column(name = "RunningTime", nullable = false)
	public String getRunningTime() {
		return this.runningTime;
	}

	public void setRunningTime(String runningTime) {
		this.runningTime = runningTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 23)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "TotalTrip", nullable = false)
	public int getTotalTrip() {
		return this.totalTrip;
	}

	public void setTotalTrip(int totalTrip) {
		this.totalTrip = totalTrip;
	}

	@Column(name = "Status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "busTimeTable")
	public Set<BusTrip> getBusTrips() {
		return this.busTrips;
	}

	public void setBusTrips(Set<BusTrip> busTrips) {
		this.busTrips = busTrips;
	}

}
