package com.lampnc.businfo.entity;
// Generated Nov 18, 2016 5:58:34 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BusTimeTableId generated by hbm2java
 */
@Embeddable
public class BusTimeTableId implements java.io.Serializable {

	private int planId;
	private int timeTableId;

	public BusTimeTableId() {
	}

	public BusTimeTableId(int planId, int timeTableId) {
		this.planId = planId;
		this.timeTableId = timeTableId;
	}

	@Column(name = "PlanId", nullable = false)
	public int getPlanId() {
		return this.planId;
	}

	public void setPlanId(int planId) {
		this.planId = planId;
	}

	@Column(name = "TimeTableId", nullable = false)
	public int getTimeTableId() {
		return this.timeTableId;
	}

	public void setTimeTableId(int timeTableId) {
		this.timeTableId = timeTableId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BusTimeTableId))
			return false;
		BusTimeTableId castOther = (BusTimeTableId) other;

		return (this.getPlanId() == castOther.getPlanId()) && (this.getTimeTableId() == castOther.getTimeTableId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlanId();
		result = 37 * result + this.getTimeTableId();
		return result;
	}

}
